version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - /mnt/c/Users/andre/volumes/mysql:/banco.sql
      - ./outros/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./outros/data.sql:/docker-entrypoint-initdb.d/2.sql
