version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banco
    ports:
      - "3306:3306"
    volumes:
      - /mnt/c/Users/andre/volumes/mysql:/banco.sql
