version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: minicloud
    ports:
      - "3307:3306"
    volumes:
      - /mnt/c/Users/andre/volumes/mysql:/minicloud.sql
